name: Development Workflow


on:
  push: 
    branches: [ development ] # is triggered if push event in release branch occurs

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest # run ubuntu

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3 # checkout your repo - this is an official action provided by GitHub
    - name: Setup
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
    - name: dependencies
      run: npm ci
    - name: Run tests
      run: npm run test --if-present
    - name: ESLinter
      run: npm run lint --if-present
